=== mannau/boilerpipeR/java/xerces-java-trunk/proposals/XRI-requirements/issues.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.0 (http://www.xmlspy.com) by Edward Staub (private) -->
<!--DTD generated by XML Spy v3.0 (http://www.xmlspy.com)-->
<!ENTITY nbsp "&#160;">
<!ELEMENT a (strong | em)>
<!ATTLIST a
	href CDATA #IMPLIED
	name CDATA #IMPLIED
>
<!ELEMENT cat (#PCDATA)>
<!ELEMENT categories (cat+)>
<!ELEMENT def (#PCDATA | br | a | ul)*>

<!ELEMENT br EMPTY>
<!ELEMENT seeAlso EMPTY>
<!ELEMENT edReqNote (#PCDATA)>
<!ELEMENT em (#PCDATA | small)*>
<!ELEMENT li (#PCDATA | a | em | ul)*>
<!ELEMENT small (#PCDATA)>
<!ELEMENT strong (#PCDATA)>
<!ELEMENT ul (li*)>
<!ELEMENT mailHeaderSet (li+)>
<!ATTLIST mailHeaderSet
	id (gen | xdev) #REQUIRED
>
<!ELEMENT mailHeaderSets (mailHeaderSet+)>
<!ELEMENT ref (#PCDATA | br)*>
<!ATTLIST ref
	set CDATA #REQUIRED
	id CDATA #REQUIRED
>
<!ELEMENT refs (ref)*>
<!ELEMENT voteSet (vote*)>
<!ATTLIST voteSet
	opened CDATA #REQUIRED
	closed CDATA #REQUIRED
	callForVote CDATA #IMPLIED
>
<!ELEMENT vote (voteComment?)>
<!ATTLIST vote
	voter CDATA #REQUIRED
	email CDATA #REQUIRED
	vote CDATA #REQUIRED
>
<!ELEMENT voteComment (#PCDATA)>
<!ELEMENT req (def, seeAlso*, edReqNote*, voteSet?, refs)>
<!ATTLIST req
	status (approved | tooQuiet | hardnessConflict | vetoConflict | rejected | unevaluated) "unevaluated"
	id CDATA #REQUIRED
	strength (hard | soft) #REQUIRED
	cat CDATA #REQUIRED
>
<!ATTLIST seeAlso
	id CDATA #REQUIRED
	type (Conflict) #IMPLIED
>
<!ELEMENT requirementCatalog (categories, requirements, mailHeaderSets)>
<!ATTLIST requirementCatalog
	date CDATA #REQUIRED
	version CDATA #REQUIRED
>
<!ELEMENT requirements (req+)>

=== mannau/boilerpipeR/java/xerces-java-trunk/proposals/XRI-requirements/issues.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.0 (http://www.xmlspy.com) by Edward Staub (private) -->
<?xml-stylesheet type="text/xsl" href="issues.xsl"?>
<!DOCTYPE requirementCatalog SYSTEM "issues.dtd">
<requirementCatalog date="15 September 2000" version="1.5">
	<!-- Checked apache general list through messages 2091 through 2375 -->
	<!-- Checked apache xerces-j-dev list messages 1160 through 1380 -->
	<categories>
		<cat>Architecture</cat>
		<cat>Standards</cat>
		<cat>Features</cat>
		<cat>Memory</cat>
		<cat>Speed</cat>
		<cat>Quality</cat>
		<cat>Other</cat>
	</categories>
	<requirements>
		<req id="1" status="approved" strength="hard" cat="Quality">
			<def>The code shall be maintainable and simple to read.</def>
			<seeAlso id="5"/>
			<voteSet opened="26-Aug-00" closed="15-Sept-00">
				<vote voter="Curt Arnold" email="CurtA@techie.com" vote="+1">
					<voteComment>+1 on intent.  But how can this be a "shall" when there is not a measure
for maintainability or simplicity.  Are there specific criteria that we
want to establish such as the Sun's Java coding conventions or something
else from the Apache world?
</voteComment>
				</vote>
				<vote voter="Chris Laprun" email="chris.laprun@nist.gov" vote="+1"/>
				<vote voter="Ted Leung" email="twleung@sauria.com" vote="+1"/>
				<vote voter="James Duncan Davidson" email="duncan@x180.com" vote="+1">
					<voteComment>I have an easy way to measure this.. Committers should only be committers if
they are prepared to read the code commits. If the code commit isn't
readable to somebody and they throw a flag, then it probably fails the test.
For example, my criteria on such code would be that I can understand it. If
everybody's criteria is this, then it works.
</voteComment>
				</vote>
				<vote voter="Mikael Helbo Kjaer" email="mhk@dia.dk" vote="+1"/>
				<vote voter="Jeffrey Rodriguez" email="jeffreyr_97@hotmail.com" vote="+1"/>
				<vote voter="Arnaud Le Hors" email="lehors@us.ibm.com" vote="+1"/>
				<vote voter="Assaf Arkin" email="arkin@arkin.exoffice.com" vote="+1"/>
				<vote voter="Eric Ye" email="ericye@locus.apache.org" vote="+1"/>
				<vote voter="Edwin Goei" email="Edwin.Goei@eng.sun.com" vote="+1"/>
			</voteSet>
			<refs>
				<ref set="gen" id="2091"> Above all, this is the primary goal        for any openly developed project as without the ability to read the        code, it's impossible for people to contribute and get involved.</ref>
				<ref set="gen" id="2138"/>
				<ref set="gen" id="2186">[current code too complex, scares off users]</ref>
				<ref set="gen" id="2209">I don't think I am [willing to trade off some performance for clearly written code]. Performance is too damned important in the XML  world</ref>
				<ref set="gen" id="2220">You're not going to get a diverse developer community built around code that  is too damned hard to read... </ref>
				<ref set="gen" id="2311"/>
			</refs>
		</req>
		<req id="2" status="approved" strength="soft" cat="Memory">
			<def>The parser should have a competitive memory footprint (competitive
against the other Java based parsers out there).
</def>
			<seeAlso id="3"/>
			<voteSet opened="26-Aug-00" closed="15-Sept-00">
				<vote voter="Curt Arnold" email="CurtA@techie.com" vote="+1">
					<voteComment>I assume that the comparison would be some basket of scenarios, so
that being efficient with large documents could offset a slightly
greater initial load size.</voteComment>
				</vote>
				<vote voter="Chris Laprun" email="chris.laprun@nist.gov" vote="+1"/>
				<vote voter="Ted Leung" email="twleung@sauria.com" vote="+1"/>
				<vote voter="James Duncan Davidson" email="duncan@x180.com" vote="+1"/>
				<vote voter="Mikael Helbo Kjaer" email="mhk@dia.dk" vote="+1"/>
				<vote voter="Jeffrey Rodriguez" email="jeffreyr_97@hotmail.com" vote="+1"/>
				<vote voter="Arnaud Le Hors" email="lehors@us.ibm.com" vote="+1"/>
				<vote voter="Assaf Arkin" email="arkin@arkin.exoffice.com" vote="+1"/>
				<vote voter="Eric Ye" email="ericye@locus.apache.org" vote="+0"/>
				<vote voter="Edwin Goei" email="Edwin.Goei@eng.sun.com" vote="+1"/>
			</voteSet>
			<refs>
				<ref set="gen" id="2091">This means small distribution size (JAR file)        and small memory footprint.</ref>
				<ref set="gen" id="2203"/>
				<ref set="gen" id="2341"/>
				<ref set="gen" id="2345"/>
			</refs>
		</req>
		<req id="3" status="approved" strength="hard" cat="Architecture">
			<def>The parser shall be designed so as to allow deployment of minimal subsets suitable for low-end, memory-constrained applications
			<br/>The build process shall create both:
<ul>
					<li>a .jar file containing all standard components of Xerces (xerces.jar).</li>
					<li>a set of .jar files which together contain everything in xerces.jar, broken into the following components:
<ul>
							<li>xerces kernel, which supports the “internal APIs” and SAX support</li>
							<li>DOM support</li>
							<li>Validation support</li>
							<li>other components of large size which can be easily factored and for which there is a significant audience who will benefit from not including them in a deployment.</li>
						</ul>
					</li>
				</ul>
			</def>
			<seeAlso id="2"/>
			<seeAlso id="13"/>
			<voteSet opened="26-Aug-00" closed="15-Sept-00">
				<vote voter="Curt Arnold" email="CurtA@techie.com" vote="+1">
					<voteComment>If this type of surgery is possible, then it should help
requirement 2 since loading unused classes could be avoided.
</voteComment>
				</vote>
				<vote voter="Chris Laprun" email="chris.laprun@nist.gov" vote="+1"/>
				<vote voter="Ted Leung" email="twleung@sauria.com" vote="+1"/>
				<vote voter="James Duncan Davidson" email="duncan@x180.com" vote="+1"/>
				<vote voter="Mikael Helbo Kjaer" email="mhk@dia.dk" vote="+1"/>
				<vote voter="Jeffrey Rodriguez" email="jeffreyr_97@hotmail.com" vote="+1"/>
				<vote voter="Arnaud Le Hors" email="lehors@us.ibm.com" vote="+1"/>
				<vote voter="Assaf Arkin" email="arkin@arkin.exoffice.com" vote="+1"/>
				<vote voter="Eric Ye" email="ericye@locus.apache.org" vote="+1"/>
				<vote voter="Edwin Goei" email="Edwin.Goei@eng.sun.com" vote="+1"/>
			</voteSet>
			<refs>
				<ref set="gen" id="2091">It should be possible to build a parser as a set of Jar files        so that a smaller parser can be assembled which fits the need of a        particular implementation. For example, in TV sets do you really need        validation?</ref>
				<ref set="gen" id="2223">Where I am now we use XML as a wire format, so the data volume is small,  and parsing takes place on the client (the customer's e-commerce  environment) and on the server. Small footprint (memory *and* disk)  are much more important in this context than speed or even validation.  </ref>
				<ref set="gen" id="2223">... many applications could benefit ...</ref>
				<ref set="xdev" id="1324">"small-but-performant-ambitious"  devices vs. "as-small-and-cheap-as-possible" devices</ref>
				<ref set="xdev" id="1361">I [am] a proponent [of support for] "small-but-perfrormant-ambitious", not  "as-small-and-cheap-as-possible" [devices] </ref>
			</refs>
		</req>
		<req id="4" status="approved" strength="hard" cat="Speed">
			<def>The parser shall run well on all virutal machines and 			shall not be optimized toward a particular virtual machine.</def>
			<refs>
				<ref set="gen" id="2091"/>
				<ref set="xdev" id="1299"/>
				<ref set="xdev" id="1307"/>
			</refs>
		</req>
		<req id="5" status="approved" strength="soft" cat="Quality">
			<def>Optimizations that interfere with readability,        modularity, or size should be shunned.  </def>
			<seeAlso id="1"/>
			<refs>
				<ref set="gen" id="2091"/>
			</refs>
		</req>
		<req id="6" status="rejected" strength="soft" cat="Memory">
			<def>The parser should have the smallest possible distribution (JAR) size.</def>
			<seeAlso id="3"/>
			<edReqNote>The votes below were votes to remove this requirement.  Its concerns are addressed elsewhere.</edReqNote>
			<voteSet opened="26-Aug-00" closed="15-Sept-00">
				<vote voter="Curt Arnold" email="CurtA@techie.com" vote="+1 to remove"/>
				<vote voter="Chris Laprun" email="chris.laprun@nist.gov" vote="+1 to remove"/>
				<vote voter="Ted Leung" email="twleung@sauria.com" vote="+1 to remove"/>
				<vote voter="James Duncan Davidson" email="duncan@x180.com" vote="+1 to remove"/>
				<vote voter="Mikael Helbo Kjaer" email="mhk@dia.dk" vote="+1 to remove"/>
				<vote voter="Jeffrey Rodriguez" email="jeffreyr_97@hotmail.com" vote="+1 to remove"/>
				<vote voter="Arnaud Le Hors" email="lehors@us.ibm.com" vote="+1 to remove"/>
				<vote voter="Assaf Arkin" email="arkin@arkin.exoffice.com" vote="+1 to remove"/>
				<vote voter="Eric Ye" email="ericye@locus.apache.org" vote="+1 to remove"/>
				<vote voter="Edwin Goei" email="Edwin.Goei@eng.sun.com" vote="+1 to remove"/>
			</voteSet>
			<refs>
				<ref set="gen" id="2091">This means small distribution size (JAR file)        and small memory footprint.  </ref>
				<ref set="gen" id="2093">These two requirements [small memory footprint, small jar size -ed] are in direct conflict.   </ref>
			</refs>
		</req>
		<req id="7" status="approved" strength="soft" cat="Quality">
			<def>The design of the parser should be documented, with diagrams where they are more expressive than text.</def>
			<voteSet opened="26-Aug-00" closed="15-Sept-00">
				<vote voter="Curt Arnold" email="CurtA@techie.com" vote="+0"/>
				<vote voter="Chris Laprun" email="chris.laprun@nist.gov" vote="+1"/>
				<vote voter="Ted Leung" email="twleung@sauria.com" vote="+1"/>
				<vote voter="James Duncan Davidson" email="duncan@x180.com" vote="+1"/>
				<vote voter="Mikael Helbo Kjaer" email="mhk@dia.dk" vote="+1"/>
				<vote voter="Jeffrey Rodriguez" email="jeffreyr_97@hotmail.com" vote="+1"/>
				<vote voter="Arnaud Le Hors" email="lehors@us.ibm.com" vote="+1"/>
